export enum ButtonType {
    H1 = "Heading1",
    H2 = "Heading2",
    H3 = "Heading3",
    Bold = "Bold",
    Italic = "Italic",
    Underline = "Underline",
    AlignLeft = "AlignLeft",
    AlignCenter = "AlignCenter",
    AlignRight = "AlignRight",
    Paintbrush = "Paintbrush",
    Text = "Text",
    Link = "Hyperlink",
    Quote = "Quote",
    Code = "Code",
    Trash = "Trash",
    Save = "Save",
    Upload = "Upload",
    Separator = "Separator"
}
